version: '3.9'

services:
   
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always

  api:
    build: .
    ports:
       - 4000:3000
    environment:
      DB_USERNAME: "********"
      DB_PASSWORD: "*******"
      DB_APPPASSWORD : "**** **** **** ****"
    depends_on:
     - mongo_db
